In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.0.2


In [4]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", array_3d)

1D Array: [1 2 3 4]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Shape: (2, 3)
Size: 6
Data Type: int64


In [6]:
array_1d = np.array([1, 2, 3, 4])
# Output: 1D Array: [1 2 3 4], Shape: (4,), Size: 4
array_1d

array([1, 2, 3, 4])

In [7]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d
# Shape: (2, 3), Size: 6

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d
# Shape: (2, 2, 2), Size: 8

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
np.zeros((3, 2))  # 3 rows, 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros((2, 3), dtype=int) #np.array([1, 2, 3], dtype=float) #np.zeros((2, 3), dtype=np.float64)
#arr.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
random_array_2d = np.random.randint(1, 11, size=(2, 5))
print("\n2D Random Array (2x5):\n", random_array_2d)
print("Shape:", random_array_2d.shape)


2D Random Array (2x5):
 [[6 6 6 3 5]
 [2 8 2 7 7]]
Shape: (2, 5)


In [13]:
pixels = np.random.randint(0, 256, size=(3, 3, 3))
print("\n3D Pixel Array (Image - 3x3 pixels, RGB):\n", pixels)
print("Shape:", pixels.shape)


3D Pixel Array (Image - 3x3 pixels, RGB):
 [[[167 168  99]
  [ 69 105 216]
  [143  38 224]]

 [[112 224 121]
  [124 167  70]
  [235 150 195]]

 [[218 192 119]
  [164 221  43]
  [177 228 255]]]
Shape: (3, 3, 3)


In [14]:
# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [15]:
# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [16]:
# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array

Result of Boolean Indexing: [4 5 6]


In [17]:
# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

First element: 10
First three elements: [10 20 30]


In [18]:
# Boolean indexing
print("Elements greater than 25:", array[array > 25])

# Fancy indexing (using a list of indices)
print("Select specific elements:", array[[1, 3]])

Elements greater than 25: [30 40 50]
Select specific elements: [20 40]


In [20]:
# 1. Basic Indexing: Create an array of 10 elements
arr = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

# Access the 5th element (index 4)
fifth_element = arr[4]
print("5th element:", fifth_element)

# 2. Basic Slicing: Extract 3rd to 8th elements (index 2 to 7)
slice_3_to_8 = arr[2:8]
print("Slice from 3rd to 8th element:", slice_3_to_8)

# 3. Boolean Indexing: Create array of 6 random integers from 10 to 50
random_array = np.random.randint(10, 51, size=6)
greater_than_30 = random_array[random_array > 30]
print("Random array:", random_array)
print("Elements > 30:", greater_than_30)

# 4. Fancy Indexing: Access 2nd, 4th, and 6th elements (indices 1, 3, 5)
fancy_selected = random_array[[1, 3, 5]]
print("Fancy indexing (2nd, 4th, 6th):", fancy_selected)

5th element: 4
Slice from 3rd to 8th element: [2 3 4 5 6 7]
Random array: [24 46 44 26 33 36]
Elements > 30: [46 44 33 36]
Fancy indexing (2nd, 4th, 6th): [46 26 36]


In [21]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([7, 1, 2, 3, 5, 6, 4])

In [22]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[5, 6],
       [3, 4],
       [1, 2]])

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10  # Changing the third element
print(arr)  # Output: [1, 2, 10, 4, 5]

[ 1  2 10  4  5]


In [26]:
arr[1:4] = [20, 30, 40]
print(arr)  # Output: [1, 20, 30, 40, 5]

[ 1 20 30 40  5]


In [27]:
arr[arr > 10] = 100
print(arr)  # Output: [1, 100, 100, 100, 5]

[  1 100 100 100   5]


In [28]:
arr[np.array([1, 3])] = 500
print(arr)  # Output: [1, 500, 100, 500, 5]

[  1 500 100 500   5]


In [29]:
sub_arr = arr[1:3]
sub_arr[0] = 600
print(arr)  # Output: [1, 600, 100, 500, 5]

[  1 600 100 500   5]


In [30]:
# 1. Modifying Specific Elements
arr1 = np.arange(1, 11)  # [1 2 3 4 5 6 7 8 9 10]
arr1[4] = 50  # 5th element (index 4) set to 50
print("1. Modified 5th element:", arr1)

# 2. Slicing and Modifying a Range
arr2 = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
arr2[3:8] = -arr2[3:8]  # Negate elements from index 3 to 7
print("2. Negative from index 3 to 7:", arr2)

# 3. Conditional Modification with Boolean Indexing
arr3 = np.random.randint(1, 101, size=20)
arr3[arr3 > 50] = -1  # Set elements > 50 to -1
print("3. Random array with values > 50 set to -1:\n", arr3)

# 4. Advanced Indexing Modification (2D Diagonal)
arr4 = np.random.randint(1, 10, size=(5, 5))
print("4. Original 2D array:\n", arr4)
diag_indices = np.arange(5)
arr4[diag_indices, diag_indices] *= 2  # Double the diagonal elements
print("   Modified diagonal doubled:\n", arr4)

# 5. Understanding Slicing Impact
arr5 = np.arange(10)
slice_view = arr5[2:6]  # This is a view, not a copy
slice_view[0] = 99  # Modify first element of the slice
print("5. Slice modification affects original array:")
print("   Modified slice:", slice_view)
print("   Original array:", arr5)

1. Modified 5th element: [ 1  2  3  4 50  6  7  8  9 10]
2. Negative from index 3 to 7: [ 0  1  2 -3 -4 -5 -6 -7  8  9]
3. Random array with values > 50 set to -1:
 [ 4 -1  9 -1 22 -1 -1 11 -1 10 41 27 -1 48 -1 36 -1 -1 42 -1]
4. Original 2D array:
 [[4 3 1 1 2]
 [2 3 2 5 6]
 [7 1 6 8 5]
 [6 7 3 2 5]
 [4 3 9 8 1]]
   Modified diagonal doubled:
 [[ 8  3  1  1  2]
 [ 2  6  2  5  6]
 [ 7  1 12  8  5]
 [ 6  7  3  4  5]
 [ 4  3  9  8  2]]
5. Slice modification affects original array:
   Modified slice: [99  3  4  5]
   Original array: [ 0  1 99  3  4  5  6  7  8  9]


In [31]:
# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [32]:
# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [33]:
# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [35]:
# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [36]:
# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]


In [37]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6


In [38]:
# 1. Arithmetic Operations
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

add = a + b           # Element-wise addition
sub = a - b           # Element-wise subtraction
mul = a * b           # Element-wise multiplication
div = a / b           # Element-wise division

print("1. Arithmetic Operations:")
print("a:", a)
print("b:", b)
print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)

# 2. Aggregation Functions
print("\n2. Aggregation Functions:")
print("a - sum:", np.sum(a), "mean:", np.mean(a), "min:", np.min(a), "max:", np.max(a))
print("b - sum:", np.sum(b), "mean:", np.mean(b), "min:", np.min(b), "max:", np.max(b))

# 3. Broadcasting with Scalar
scalar_mul = a * 5
print("\n3. Broadcasting with Scalar (a * 5):", scalar_mul)


1. Arithmetic Operations:
a: [2 4 6]
b: [1 3 5]
Addition: [ 3  7 11]
Subtraction: [1 1 1]
Multiplication: [ 2 12 30]
Division: [2.         1.33333333 1.2       ]

2. Aggregation Functions:
a - sum: 12 mean: 4.0 min: 2 max: 6
b - sum: 9 mean: 3.0 min: 1 max: 5

3. Broadcasting with Scalar (a * 5): [10 20 30]


In [39]:
# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9
print("1D Array:", array)
# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

1D Array: [1 2 3 4 5 6 7 8 9]
Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# Transposing the reshaped array
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:

# 1. Reshape Array
arr = np.arange(1, 13)  # 1D array with 12 elements: [1 2 3 ... 12]
matrix_4x3 = arr.reshape(4, 3)  # reshape to 4 rows, 3 columns
matrix_2x6 = arr.reshape(2, 6)  # reshape to 2 rows, 6 columns

print("1. Reshaped Arrays:")
print("Original 1D array:", arr)
print("4x3 matrix:\n", matrix_4x3)
print("2x6 matrix:\n", matrix_2x6)

# 2. Transpose Matrix
transposed_2x6 = matrix_2x6.T  # transpose of 2x6 is 6x2
print("\n2. Transposed 2x6 matrix (now 6x2):\n", transposed_2x6)

# 3. Combine Reshaping and Transposing
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
transposed = matrix_3x4.T  # shape becomes 4x3
flattened = transposed.reshape(-1)  # reshape to 1D

print("\n3. Combining Transpose and Reshape:")
print("Original 3x4 matrix:\n", matrix_3x4)
print("Transposed (4x3):\n", transposed)
print("Flattened to 1D:", flattened)

1. Reshaped Arrays:
Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
4x3 matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2x6 matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

2. Transposed 2x6 matrix (now 6x2):
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]

3. Combining Transpose and Reshape:
Original 3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed (4x3):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Flattened to 1D: [ 1  5  9  2  6 10  3  7 11  4  8 12]


In [43]:
# Reshaping data for machine learning model
data = np.arange(1, 101).reshape(20, 5)  # 20 samples, 5 features each
data

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [44]:
# Preparing data for heatmap visualization
matrix = np.random.rand(10, 10)
print(matrix)
reshaped_matrix = matrix.reshape(5, 20)  # Reshaping for a different visual representation
reshaped_matrix

[[0.84745176 0.4987085  0.37973497 0.02317181 0.23641399 0.95188322
  0.73115909 0.33384752 0.36856168 0.87120952]
 [0.45969741 0.61292626 0.3537426  0.66011371 0.04328414 0.27724239
  0.88121341 0.44684537 0.55931815 0.98602775]
 [0.35474331 0.81737807 0.14751744 0.30319108 0.42975686 0.57606946
  0.3278438  0.97426956 0.65365593 0.00866262]
 [0.02757537 0.67576352 0.94299242 0.54422763 0.22378603 0.66417521
  0.16600794 0.14286109 0.34571419 0.72130561]
 [0.83447979 0.36397587 0.01626867 0.98788752 0.93464564 0.01325884
  0.09590303 0.71453789 0.31968086 0.75282583]
 [0.63164741 0.15751695 0.18096912 0.77716782 0.6296905  0.40709321
  0.12254991 0.53836153 0.27600346 0.01680843]
 [0.3555974  0.17255314 0.48229738 0.9068594  0.78889149 0.20509518
  0.64357414 0.52781716 0.19149502 0.1419164 ]
 [0.07982336 0.38626755 0.89290917 0.30450979 0.28914799 0.4040676
  0.68216127 0.42473361 0.68775047 0.73924607]
 [0.72295893 0.66845776 0.08683995 0.30301523 0.90857897 0.19373252
  0.01691046 

array([[0.84745176, 0.4987085 , 0.37973497, 0.02317181, 0.23641399,
        0.95188322, 0.73115909, 0.33384752, 0.36856168, 0.87120952,
        0.45969741, 0.61292626, 0.3537426 , 0.66011371, 0.04328414,
        0.27724239, 0.88121341, 0.44684537, 0.55931815, 0.98602775],
       [0.35474331, 0.81737807, 0.14751744, 0.30319108, 0.42975686,
        0.57606946, 0.3278438 , 0.97426956, 0.65365593, 0.00866262,
        0.02757537, 0.67576352, 0.94299242, 0.54422763, 0.22378603,
        0.66417521, 0.16600794, 0.14286109, 0.34571419, 0.72130561],
       [0.83447979, 0.36397587, 0.01626867, 0.98788752, 0.93464564,
        0.01325884, 0.09590303, 0.71453789, 0.31968086, 0.75282583,
        0.63164741, 0.15751695, 0.18096912, 0.77716782, 0.6296905 ,
        0.40709321, 0.12254991, 0.53836153, 0.27600346, 0.01680843],
       [0.3555974 , 0.17255314, 0.48229738, 0.9068594 , 0.78889149,
        0.20509518, 0.64357414, 0.52781716, 0.19149502, 0.1419164 ,
        0.07982336, 0.38626755, 0.89290917, 0

In [45]:
# Aggregating data after reshaping
data = np.random.rand(6, 2)
print(data)
reshaped_data = data.reshape(3, 4)
print(reshaped_data)
mean_values = np.mean(reshaped_data, axis=1)  # Mean of each reshaped group
mean_values

[[0.46000485 0.24014765]
 [0.49880161 0.88444906]
 [0.00911208 0.09665451]
 [0.43407534 0.11588765]
 [0.40174543 0.34850664]
 [0.45552061 0.78631579]]
[[0.46000485 0.24014765 0.49880161 0.88444906]
 [0.00911208 0.09665451 0.43407534 0.11588765]
 [0.40174543 0.34850664 0.45552061 0.78631579]]


array([0.52085079, 0.1639324 , 0.49802212])

In [46]:
# Organizing data for feature selection
data = np.random.rand(100, 10)  # 100 observations, 10 features
reshaped_data = data.reshape(100, 5, 2)  # Grouping features for analysis
reshaped_data

array([[[3.39489828e-01, 2.45858755e-02],
        [9.36528389e-01, 5.53639173e-01],
        [8.05403559e-01, 8.64983373e-01],
        [2.86426841e-01, 2.46350243e-01],
        [4.55605726e-01, 7.60349082e-01]],

       [[8.74212422e-01, 6.39368637e-01],
        [7.57145128e-01, 8.52330088e-01],
        [3.78881083e-01, 6.97220327e-01],
        [1.39487504e-01, 9.10498977e-01],
        [4.49405974e-01, 7.00746188e-01]],

       [[3.33788672e-01, 2.98335057e-01],
        [5.27209034e-01, 1.12038299e-01],
        [7.97334039e-01, 3.62859663e-01],
        [7.41136532e-02, 2.94739612e-01],
        [1.15012160e-01, 3.94311252e-01]],

       [[3.95515291e-02, 9.16953729e-01],
        [4.04341556e-02, 1.46084696e-01],
        [5.52077322e-01, 8.93478696e-01],
        [2.74196681e-01, 4.65368684e-01],
        [7.78183848e-01, 7.61611854e-01]],

       [[9.45657700e-01, 9.02711964e-01],
        [5.87428350e-01, 6.38080297e-01],
        [8.20834146e-01, 6.31214505e-01],
        [2.24254659e-01, 6

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
# or
#t = a @ b #dot product
result

np.int64(32)

In [48]:
# Reshaping data for time-series analysis
time_series_data = np.random.rand(365)  # Daily data for a year
#reshaped_for_analysis = time_series_data.reshape(52, 7)  # Weekly data, 7 days a week
reshaped_for_analysis = time_series_data[:364].reshape(52, 7)
reshaped_for_analysis

array([[0.01429287, 0.14681769, 0.18415599, 0.15196516, 0.31124479,
        0.24547368, 0.03271851],
       [0.12947037, 0.38540128, 0.52910113, 0.55307024, 0.07397917,
        0.05187091, 0.67409051],
       [0.69186527, 0.74513603, 0.19818323, 0.48263837, 0.08204405,
        0.61379031, 0.79833857],
       [0.21541425, 0.68189441, 0.98422607, 0.88700408, 0.7028494 ,
        0.40325893, 0.28987824],
       [0.75855527, 0.3571945 , 0.20537928, 0.32312497, 0.44617499,
        0.16091726, 0.07970273],
       [0.31176305, 0.5463161 , 0.13080468, 0.41020951, 0.33830977,
        0.9023975 , 0.22881751],
       [0.82909002, 0.66929554, 0.27635819, 0.16179362, 0.21503002,
        0.74703491, 0.41366007],
       [0.99746424, 0.54917726, 0.10131519, 0.66940627, 0.93900363,
        0.29267908, 0.23690358],
       [0.36536198, 0.85332384, 0.29993318, 0.67125616, 0.05800789,
        0.52065694, 0.1574142 ],
       [0.77184801, 0.67213675, 0.13540881, 0.68718966, 0.37202662,
        0.27596953, 0.0