In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.0.2


In [4]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", array_3d)

1D Array: [1 2 3 4]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Shape: (2, 3)
Size: 6
Data Type: int64


In [9]:
array_1d = np.array([1, 2, 3, 4])
# Output: 1D Array: [1 2 3 4], Shape: (4,), Size: 4
print(array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)

[1 2 3 4]
Shape: (4,)
Size: 4


In [10]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d
# Shape: (2, 3), Size: 6

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d
# Shape: (2, 2, 2), Size: 8

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
np.zeros((3, 2))  # 3 rows, 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros((2, 3), dtype=int) #np.array([1, 2, 3], dtype=float) #np.zeros((2, 3), dtype=np.float64)
#arr.astype(int)




array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [16]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [17]:
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array

Result of Boolean Indexing: [4 5 6]


In [18]:
import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

First element: 10
First three elements: [10 20 30]


In [19]:
# Boolean indexing
print("Elements greater than 25:", array[array > 25])

# Fancy indexing (using a list of indices)
print("Select specific elements:", array[[1, 3]])

Elements greater than 25: [30 40 50]
Select specific elements: [20 40]


In [20]:
rand = np.random.randint(10, 50, 6)
print(rand)
print(rand[rand>30])

[47 48 37 32 32 36]
[47 48 37 32 32 36]


In [21]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([2, 7, 1, 4, 6, 5, 3])

In [22]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[1, 2],
       [5, 6],
       [3, 4]])

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10  # Changing the third element
print(arr)  # Output: [1, 2, 10, 4, 5]

[ 1  2 10  4  5]


In [25]:
arr[1:4] = [20, 30, 40]
print(arr)  # Output: [1, 20, 30, 40, 5]

[ 1 20 30 40  5]


In [26]:
arr[arr > 10] = 100
print(arr)  # Output: [1, 100, 100, 100, 5]

[  1 100 100 100   5]


In [27]:
arr[np.array([1, 3])] = 500
print(arr)  # Output: [1, 500, 100, 500, 5]

[  1 500 100 500   5]


In [28]:
sub_arr = arr[1:3]
sub_arr[0] = 600
print(arr)  # Output: [1, 600, 100, 500, 5]

[  1 600 100 500   5]


In [29]:
import numpy as np

# --------------------------
# 1. Basic Indexing
# --------------------------
array_basic = np.arange(1, 11)  # Creates array [1, 2, ..., 10]
fifth_element = array_basic[4]  # Indexing starts at 0, so 5th element is at index 4

print("1. 5th Element:", fifth_element)

# --------------------------
# 2. Basic Slicing
# --------------------------
slice_3_to_8 = array_basic[2:8]  # 3rd to 8th element → indices 2 to 7
print("2. Slice from 3rd to 8th:", slice_3_to_8)

# --------------------------
# 3. Boolean Indexing
# --------------------------
random_array = np.random.randint(10, 51, size=6)  # 6 random integers between 10 and 50
greater_than_30 = random_array[random_array > 30]

print("3. Random Array:", random_array)
print("   Elements > 30:", greater_than_30)

# --------------------------
# 4. Fancy Indexing
# --------------------------
# Access 2nd, 4th, and 6th elements → indices 1, 3, 5
fancy_selected = random_array[[1, 3, 5]]
print("4. Fancy Indexing (2nd, 4th, 6th):", fancy_selected)


1. 5th Element: 5
2. Slice from 3rd to 8th: [3 4 5 6 7 8]
3. Random Array: [24 11 12 48 35 20]
   Elements > 30: [48 35]
4. Fancy Indexing (2nd, 4th, 6th): [11 48 20]


In [30]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [31]:
# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [32]:
import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [34]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [33]:
import numpy as np

# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [35]:
# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a:", a)
print("Array b:", b)
print("Broadcasted Addition:", result)

Array a: [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [36]:
import numpy as np

# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]


In [37]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6


In [39]:
import numpy as np

# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9
print("1D Array:", array)
# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

1D Array: [1 2 3 4 5 6 7 8 9]
Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# Transposing the reshaped array
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
# Reshaping data for machine learning model
data = np.arange(1, 101).reshape(20, 5)  # 20 samples, 5 features each
data

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [42]:
# Preparing data for heatmap visualization
matrix = np.random.rand(10, 10)
print(matrix)
reshaped_matrix = matrix.reshape(5, 20)  # Reshaping for a different visual representation
reshaped_matrix

[[0.64424228 0.03019175 0.15828421 0.69578965 0.08707587 0.43183822
  0.0731665  0.50332739 0.55566914 0.78457225]
 [0.8684816  0.40746516 0.83451213 0.22140982 0.80324179 0.40150983
  0.98716334 0.38285296 0.44920894 0.00707076]
 [0.18126607 0.77216739 0.25859269 0.34604024 0.63058982 0.11511415
  0.38110599 0.64478032 0.03203057 0.17980441]
 [0.58663051 0.26691271 0.33852274 0.88980157 0.49292885 0.00160718
  0.20018297 0.34247711 0.87874109 0.990224  ]
 [0.60067293 0.96285381 0.85171092 0.63852024 0.32963601 0.37075713
  0.85582479 0.37259815 0.43580963 0.5729773 ]
 [0.64825911 0.47117508 0.86740318 0.68240049 0.81991316 0.11110986
  0.89651414 0.32719228 0.24851045 0.27632014]
 [0.70089816 0.53713156 0.81590691 0.86584669 0.99925531 0.14741118
  0.66426974 0.89493453 0.12085434 0.62358898]
 [0.37723027 0.70011221 0.95541739 0.56986034 0.63171132 0.42696816
  0.75131967 0.96090153 0.24217454 0.0712452 ]
 [0.8744264  0.07581483 0.07590979 0.24677713 0.12603811 0.14456136
  0.80176587

array([[0.64424228, 0.03019175, 0.15828421, 0.69578965, 0.08707587,
        0.43183822, 0.0731665 , 0.50332739, 0.55566914, 0.78457225,
        0.8684816 , 0.40746516, 0.83451213, 0.22140982, 0.80324179,
        0.40150983, 0.98716334, 0.38285296, 0.44920894, 0.00707076],
       [0.18126607, 0.77216739, 0.25859269, 0.34604024, 0.63058982,
        0.11511415, 0.38110599, 0.64478032, 0.03203057, 0.17980441,
        0.58663051, 0.26691271, 0.33852274, 0.88980157, 0.49292885,
        0.00160718, 0.20018297, 0.34247711, 0.87874109, 0.990224  ],
       [0.60067293, 0.96285381, 0.85171092, 0.63852024, 0.32963601,
        0.37075713, 0.85582479, 0.37259815, 0.43580963, 0.5729773 ,
        0.64825911, 0.47117508, 0.86740318, 0.68240049, 0.81991316,
        0.11110986, 0.89651414, 0.32719228, 0.24851045, 0.27632014],
       [0.70089816, 0.53713156, 0.81590691, 0.86584669, 0.99925531,
        0.14741118, 0.66426974, 0.89493453, 0.12085434, 0.62358898,
        0.37723027, 0.70011221, 0.95541739, 0

In [43]:
# Aggregating data after reshaping
data = np.random.rand(6, 2)
print(data)
reshaped_data = data.reshape(3, 4)
print(reshaped_data)
mean_values = np.mean(reshaped_data, axis=1)  # Mean of each reshaped group
mean_values

[[0.72035269 0.83015403]
 [0.02307733 0.63944902]
 [0.99258012 0.62768294]
 [0.91888444 0.94808423]
 [0.70825303 0.6329876 ]
 [0.03877812 0.20290431]]
[[0.72035269 0.83015403 0.02307733 0.63944902]
 [0.99258012 0.62768294 0.91888444 0.94808423]
 [0.70825303 0.6329876  0.03877812 0.20290431]]


array([0.55325827, 0.87180793, 0.39573076])

In [44]:
# Organizing data for feature selection
data = np.random.rand(100, 10)  # 100 observations, 10 features
reshaped_data = data.reshape(100, 5, 2)  # Grouping features for analysis
reshaped_data

array([[[6.08564163e-01, 6.89928135e-01],
        [4.00436452e-01, 1.39867641e-02],
        [1.05392917e-01, 7.95519948e-01],
        [1.77545418e-01, 7.68001439e-01],
        [1.53851277e-01, 3.09876851e-02]],

       [[1.96725025e-01, 5.83938569e-01],
        [5.88152766e-01, 8.91758793e-01],
        [1.18868622e-01, 8.87945402e-01],
        [5.47551531e-01, 1.22865250e-01],
        [3.61838241e-02, 7.75729654e-01]],

       [[4.14954017e-01, 4.88051938e-01],
        [6.88467727e-01, 2.36136090e-01],
        [5.62821118e-01, 6.58521023e-01],
        [8.79555680e-01, 2.24791515e-01],
        [1.14461158e-01, 7.46728025e-01]],

       [[1.34310887e-01, 1.36143722e-01],
        [8.07006298e-01, 7.06883088e-02],
        [4.20200556e-02, 2.18322986e-01],
        [2.95143253e-01, 3.74217500e-01],
        [2.10536505e-01, 3.28556665e-01]],

       [[5.99773730e-01, 1.13003327e-01],
        [4.00237875e-02, 3.97786090e-01],
        [9.19797779e-01, 2.63455864e-01],
        [5.14231245e-01, 2

In [45]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
# or
#t = a @ b #dot product
result

np.int64(32)

In [48]:
# Transposing for matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
product = A.dot(B.transpose())  # Transposing B to make multiplication possible
product

array([17, 39])

In [49]:

# Reshaping data for time-series analysis
time_series_data = np.random.rand(365)  # Daily data for a year
#reshaped_for_analysis = time_series_data.reshape(52, 7)  # Weekly data, 7 days a week
reshaped_for_analysis = time_series_data[:364].reshape(52, 7)
reshaped_for_analysis

array([[0.83645039, 0.57902561, 0.04657884, 0.22104481, 0.42275119,
        0.77206837, 0.126953  ],
       [0.82710073, 0.66262388, 0.70402753, 0.80036529, 0.72669642,
        0.69429074, 0.47670197],
       [0.11696702, 0.43970725, 0.96034529, 0.35565635, 0.12676492,
        0.85158753, 0.64216158],
       [0.69264846, 0.96049624, 0.11183474, 0.91096047, 0.42651462,
        0.81904645, 0.97171745],
       [0.8602515 , 0.40357542, 0.17343099, 0.44416631, 0.44021092,
        0.53924155, 0.20158173],
       [0.10676932, 0.92794872, 0.42423382, 0.36016471, 0.51339035,
        0.34280371, 0.02562069],
       [0.4939761 , 0.97226632, 0.46439764, 0.5480159 , 0.90943239,
        0.0899684 , 0.47260743],
       [0.76153772, 0.95135469, 0.84275666, 0.69469417, 0.26034504,
        0.62630825, 0.22606704],
       [0.25759686, 0.46557858, 0.00366858, 0.25662526, 0.37418448,
        0.21728262, 0.53984437],
       [0.6519829 , 0.60694885, 0.23966874, 0.45936689, 0.90374688,
        0.89324211, 0.3