In [1]:
import numpy as np

# Create a 1D array with numbers from 0 to 9
arr = np.arange(10)

print("Created 1D array:")
print(arr)

Created 1D array:
[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Original list
lst = [3.14, 2.17, 0, 1, 2]

# Convert to NumPy array and change data type to integer
arr = np.array(lst, dtype=int)

print("Converted array with integer data type:")
print(arr)

Converted array with integer data type:
[3 2 0 1 2]


In [4]:
# Create a 3x3 array with values from 1 to 9
arr = np.arange(1, 10).reshape(3, 3)

print("3x3 array:")
print(arr)


3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Create a 2D array of shape (4, 5) with random float numbers between 0 and 1
arr = np.random.rand(4, 5)

# Optional: round the numbers for better readability
arr = np.round(arr, 2)

print("Random 4x5 array:")
print(arr)

Random 4x5 array:
[[0.25 0.03 0.93 0.72 0.11]
 [0.39 0.86 0.62 0.84 0.86]
 [0.43 0.58 0.77 0.52 0.17]
 [0.75 0.17 0.51 1.   0.74]]


In [7]:
# Given 2D array
array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

# Select the second row (index 1)
second_row = array[1]

print("Second row of the array:")
print(second_row)


Second row of the array:
[20 21 22 23 24]


In [8]:
# Create the original 1D array
arr = np.arange(10)

# Reverse the array using slicing
reversed_arr = arr[::-1]

print("Reversed array:")
print(reversed_arr)


Reversed array:
[9 8 7 6 5 4 3 2 1 0]


In [9]:
identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

total_sum = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total_sum}, Average: {average}")

Sum: 45, Average: 4.5


In [12]:
arr = np.arange(1, 21)       # Создаём массив от 1 до 20 включительно
reshaped_arr = arr.reshape(4, 5)  # Меняем форму на 4 строки и 5 столбцов

print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]
